sudo: required
services:
    - docker 

before_install:
    - docker build -t mrbost/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run mrbost/react-test npm test -- --coverage

after_success:
    - docker build -t mrbost/multi-client ./client
    - docker build -t mrbost/multi-nginx ./nginx
    - docker build -t mrbost/multi-worker ./worker
    - docker build -t mrbost/multi-server ./server
    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push mrbost/multi-client
    - docker push mrbost/multi-nginx
    - docker push mrbost/multi-worker
    - docker push mrbost/multi-server

    deploy:
        provider: elasticbeanstalk
        region: us-west-1
        app: multi-docker
        env: Multidocker-env
        bucket_name: elasticbeanstalk-us-west-1-3064766227457
        bucket_path: docker-multi
        on:
            branch: master
        acces_key_id: $AWS_ACCESS_KEY
        secret_access_key:
            secure: $AWS_SECRET_KEY